insert into user values (1, 'Jake', 'jwilsonlax13@gmail.com')
insert into user values(2, 'John', 'John@John.com')
insert into user values(3, 'Adam', 'adam@adam.com')


insert into category values (1, 'Travel')
insert into category values(2, 'Auto Loan')
insert into category values(3, 'Student Loan')
insert into category values(4, 'General Expenses')
insert into category values(5, 'Auto Maintence')
insert into category values(6, 'Other')

insert into expense values (100, 'New York Trip', '2019-06-16T17:00:00.000Z', 'New York', 1,1)
insert into expense values (101, 'Saab 9-3arc Payment', '2019-06-15T15:00:00.000Z', 'North Carolina', 2,2)
insert into expense values (102, 'School Payment', '2019-06-14T15:00:00.000Z','Arizona', 3,1)
